alias ls='ls --color'
alias vi='vim'
alias src='source ~/.bashrc'
alias gitd='git difftool --tool=vimdiff --no-prompt'

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

# Add systemish scripts
export PATH=$PATH:/users/akalia/systemish/scripts
export PATH=$PATH:/users/akalia/systemish/scripts/dpdk

# DPDK vars
export RTE_SDK=/users/akalia/dpdk-1.5.0r0/
export RTE_TARGET=x86_64-default-linuxapp-gcc

export https_proxy=""

alias a1='ssh anuj1.RDMA.fawn.susitna.pdl.cmu.local'
alias a2='ssh anuj2.RDMA.fawn.susitna.pdl.cmu.local'
alias a3='ssh anuj3.RDMA.fawn.susitna.pdl.cmu.local'
alias a4='ssh anuj4.RDMA.fawn.susitna.pdl.cmu.local'
alias a5='ssh anuj5.RDMA.fawn.susitna.pdl.cmu.local'
alias a6='ssh anuj6.RDMA.fawn.susitna.pdl.cmu.local'
alias a7='ssh anuj7.RDMA.fawn.susitna.pdl.cmu.local'
alias a8='ssh anuj8.RDMA.fawn.susitna.pdl.cmu.local'
alias a9='ssh anuj9.RDMA.fawn.susitna.pdl.cmu.local'
alias a10='ssh anuj10.RDMA.fawn.susitna.pdl.cmu.local'
alias a11='ssh anuj11.RDMA.fawn.susitna.pdl.cmu.local'
alias a12='ssh anuj12.RDMA.fawn.susitna.pdl.cmu.local'
alias a13='ssh anuj13.RDMA.fawn.susitna.pdl.cmu.local'
alias a14='ssh anuj14.RDMA.fawn.susitna.pdl.cmu.local'
alias a15='ssh anuj15.RDMA.fawn.susitna.pdl.cmu.local'
alias a16='ssh anuj16.RDMA.fawn.susitna.pdl.cmu.local'
alias a17='ssh anuj17.RDMA.fawn.susitna.pdl.cmu.local'
alias a18='ssh anuj18.RDMA.fawn.susitna.pdl.cmu.local'
alias a19='ssh anuj19.RDMA.fawn.susitna.pdl.cmu.local'
alias a20='ssh anuj20.RDMA.fawn.susitna.pdl.cmu.local'

alias psmain='ps -afx | grep main'
